-- Create Beer table
CREATE TABLE beer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT,
    beer_name VARCHAR(255),
    beer_style VARCHAR(255),
    upc VARCHAR(255),
    quantity_on_hand INT,
    price DECIMAL(19, 2),
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);

-- Create BeerOrder table
CREATE TABLE beer_order (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT,
    customer_ref VARCHAR(255),
    payment_amount DECIMAL(19, 2),
    status VARCHAR(255),
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);

-- Create BeerOrderLine table
CREATE TABLE beer_order_line (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT,
    beer_order_id INT,
    beer_id INT,
    order_quantity INT,
    quantity_allocated INT,
    status VARCHAR(255),
    created_date TIMESTAMP,
    updated_date TIMESTAMP,
    FOREIGN KEY (beer_order_id) REFERENCES beer_order(id),
    FOREIGN KEY (beer_id) REFERENCES beer(id)
);
