-- Create BeerOrderShipment table
CREATE TABLE beer_order_shipment (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT,
    beer_order_id INT NOT NULL,
    shipment_date DATE,
    carrier VARCHAR(255),
    tracking_number VARCHAR(255),
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);

-- Add foreign key constraint to beer_order table
ALTER TABLE beer_order_shipment
    ADD CONSTRAINT fk_beer_order_shipment_beer_order FOREIGN KEY (beer_order_id) REFERENCES beer_order(id);
